### ISSUE TITLE
Invalid API server response

### ISSUE THREAD

**Issue by cyrille-legrand** [dailymotion/dailymotion-sdk-php#52]
I have a recurring project, every year in July, where I need to crawl a bunch of playlists with a cron PHP script.

This year it doesn't seem to work. I have narrowed down the issue to just rewriting your very first example : 

    <?php
    
    include('./dailymotion-sdk-php/Dailymotion.php');
    $api = new Dailymotion();
    $result = $api->get('/videos', array('fields' => array('id', 'title', 'owner')));
    echo json_encode($result);
    ?>

No matter the API call, this is what I'm getting in return:

```
PHP Fatal error:  Uncaught exception 'DailymotionApiException' with message 'Invalid API server response' in /var/www/[redacted]/video/dailymotion-sdk-php/Dailymotion.php:434
Stack trace:
#0 /var/www/[redacted]/video/dailymotion-sdk-php/Dailymotion.php(356): Dailymotion->call('GET /videos', Array)
#1 /var/www/[redacted]/video/test.php(5): Dailymotion->get('/videos', Array)
#2 {main}
  thrown in /var/www/[redacted]/video/dailymotion-sdk-php/Dailymotion.php on line 434
```

**Comment by cyrille-legrand** [comment]
Nevermind. I had a firewall missing with the DNS inbetween my server and DailyMotion's ones.
